### ISSUE TITLE
Metadata download link

### ISSUE THREAD

**Issue by jsleeo424** [mrsalehi/action-atlas#1]
First of all, thank you for your great work!

I tried to download the metadata from the given gdrive/hf link, but they seem not working.

I need permission for gdrive, while hf gives me a 404 error.

**Comment by mrsalehi** [comment]
Hi, thanks for your interest in our work!
Could you please try this link?
https://drive.google.com/file/d/1ueh5gqYg0WqQ_CFxjxsjcn8rx9wwN9Gi/view?usp=sharing

**Comment by jsleeo424** [comment]
it works, thanks!
